@isTest
private class CF_SetUltimateParentTriggerTest {
    /*private static testMethod void test() 
    {
        Test.startTest();

        Account Acc1 = new Account();
        Acc1.Name = 'Test1';
        insert Acc1;

        Account Acc2 = new Account();
        Acc2.Name = 'Test2';        
        Acc2.ParentId = Acc1.id;
        insert Acc2;
        
        Account Acc3 = new Account();
        Acc3.Name = 'Test3';        
        Acc3.ParentId = Acc3.id;
        insert Acc3;
        
        Account Acc4 = new Account();
        Acc4.Name = 'Test4';        
        Acc4.ParentId = Acc4.id;
        insert Acc4;

        Account Acc5 = new Account();
        Acc5.Name = 'Test5';        
        Acc5.ParentId = Acc5.id;
        insert Acc5;
        
        Account Acc2b = new Account();
        Acc2b.Name = 'Test2b';        
        Acc2b.ParentId = Acc1.id;
        insert Acc2b;    
        
		Account Acc1b = new Account();
        Acc1b.Name = 'Test1b';        
        insert Acc1b;    
        
        Acc2.ParentId = Acc1b.id;
        update Acc2;
        
        Test.stopTest();     
    } */  
}